#define CMD_TEX 1
#define CMD_LATEX 2
#define CMD_SLITEX 3
#define CMD_BIBTEX 4
#define CMD_LATEXE 5
#define CMD_AMSTEX 6
#define CMD_AMSLATEX 7
#define CMD_LYX 8

void            CmdCedillaChar(int code);
void            CmdUmlauteChar(int code);
void            CmdLApostrophChar(int code);
void            CmdRApostrophChar(int code);
void            CmdTildeChar(int code);
void            CmdSymbolChar(int code);
void            CmdUnderdotChar(int code);
void            CmdHacekChar(int code);
void            CmdOaccentChar(int code);
void            CmdHatChar(int code);
void            CmdMacronChar(int code);
void            CmdVecChar(int code);
void            CmdBreveChar(int code);
void            CmdDotChar(int code);
void            CmdUnderbarChar(int code);
void            CmdDotlessChar(int code);
void            CmdChar(int code);

void            CmdLogo(int code);

void 			CmdFrenchAbbrev(int code);
void			CmdCzechAbbrev(int code);
void            CmdCyrillicChar(int code);
void            CmdLatin1Char(int code);
void            CmdLatin2Char(int code);
void 			CmdCyrillicStrChar(char *s);

#define IERF 1
#define IEREF 2
#define IERSF 3
#define IERESF 4
#define IEMEF 5
#define IEMESF 6
#define DEGREE 7
#define NUMERO 8
#define NUMEROS 9
#define CNUMERO 10
#define CNUMEROS 11
#define PRIMO 12
#define SECUNDO 13
#define TERTIO 14
#define QUARTO 15
#define FUP 16

#define INFERIEURA	 17
#define SUPERIEURA	 18
#define FRENCH_LQ	 19
#define FRENCH_RQ	 20
#define FRENCH_LQQ	 21
#define FRENCH_RQQ	 22
#define POINT_VIRGULE	 23
#define POINT_EXCLAMATION	 24
#define POINT_INTERROGATION	 25
#define DITTO_MARK	 26
#define DEUX_POINTS	 27
#define LCS	 28
#define FCS	 29
#define FRENCH_OG 30
#define FRENCH_FG 31

