.\"     Title: yaz\-marcdump
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 12/17/2006
.\"    Manual: 
.\"    Source: YAZ 2.1.42
.\"
.TH "YAZ\-MARCDUMP" "1" "12/17/2006" "YAZ 2.1.42" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
yaz\-marcdump \- MARC record dump utility
.SH "SYNOPSIS"
.HP 13
\fByaz\-marcdump\fR [\fB\-i\ \fR\fB\fIformat\fR\fR] [\fB\-o\ \fR\fB\fIformat\fR\fR] [\fB\-f\ \fR\fB\fIfrom\fR\fR] [\fB\-t\ \fR\fB\fIto\fR\fR] [\fB\-l\ \fR\fB\fIspec\fR\fR] [\fB\-v\fR] [\fB\-c\ \fR\fB\fIcfile\fR\fR] [file...]
.SH "DESCRIPTION"
.PP

\fByaz\-marcdump\fR
reads MARC records from one or more files. It parses each record and supports output in line\-format, ISO2709, MARCXML, MarcXchange as well as Hex output.
.PP
This utility parses records ISO2709(raw MARC) as well as XML if that is structured as MARCXML/MarcXchange.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBNote\fR
.PP
As of YAZ 2.1.18, OAI\-MARC is no longer supported. OAI\-MARC is deprecated. Use MARCXML instead.
.PP
By default, each record is written to standard output in a line format with newline for each field, $x for each subfield x. The output format may be changed with option
\-o,
.PP

\fByaz\-marcdump\fR
can also be requested to perform character set conversion of each record.
.SH "OPTIONS"
.PP
\-i \fIformat\fR
.RS 3n
Specifies input format. Must be one of
marcxml,
marc
(ISO2709),
line
(line mode MARC).
.RE
.PP
\-o \fIformat\fR
.RS 3n
Specifies output format. Must be one of
marcxml,
marc
(ISO2709),
line
(line mode MARC).
.RE
.PP
\-f \fIfrom\fR
.RS 3n
Specify the character set
\fIfrom\fR
of the input MARC record. Should be used in conjunction with option
\-t.
.RE
.PP
\-t \fIto\fR
.RS 3n
Specify the character set
\fIof\fR
of the output. Should be used in conjunction with option
\-f.
.RE
.PP
\-l \fIleaderspec\fR
.RS 3n
Specify a simple modification string for MARC leader. The
\fIleaderspec\fR
is a list of pos=value pairs, where pos is an integer offset (0 \- 23) for leader. Value is either a quoted string or an integer (character value in decimal). Pairs are comma separated. For example, to set leader at offset 9 to a, use
9=a.
.RE
.PP
\-v
.RS 3n
Writes more information about the parsing process. Useful if you have ill\-formatted ISO2709 records as input.
.RE
.SH "EXAMPLES"
.PP
The following command converts MARC21/USMARC in MARC\-8 encoding to MARC21/USMARC in UTF\-8 encoding. Leader offset 9 is set to 'a'. Both input and output records are ISO2709 encoded.
.sp
.RS 3n
.nf
    yaz\-marcdump \-f MARC\-8 \-t UTF\-8 \-o marc \-l 9=97 marc21.raw >marc21.utf8.raw
   
.fi
.RE
.sp
.PP
The same records may be converted to MARCXML instead in UTF\-8:
.sp
.RS 3n
.nf
    yaz\-marcdump \-f MARC\-8 \-t UTF\-8 \-o marcxml marc21.raw >marcxml.xml
   
.fi
.RE
.sp
.SH "FILES"
.PP

\fI\fIprefix\fR\fR\fI/bin/yaz\-marcdump\fR
.PP

\fI\fIprefix\fR\fR\fI/include/yaz/marcdisp.h\fR
.SH "SEE ALSO"
.PP
yaz(7)
