.\"     Title: yaz\-client
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 12/17/2006
.\"    Manual: 
.\"    Source: YAZ 2.1.42
.\"
.TH "YAZ\-CLIENT" "1" "12/17/2006" "YAZ 2.1.42" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
yaz\-client \- Z39.50/SRU client for implementors
.SH "SYNOPSIS"
.HP 11
\fByaz\-client\fR [\fB\-a\ \fR\fB\fIfilename\fR\fR] [\fB\-b\ \fR\fB\fIfilename\fR\fR] [\fB\-c\ \fR\fB\fIfilename\fR\fR] [\fB\-d\ \fR\fB\fIdump\fR\fR] [\fB\-k\ \fR\fB\fIsize\fR\fR] [\fB\-m\ \fR\fB\fIfilename\fR\fR] [\fB\-p\ \fR\fB\fIaddr\fR\fR] [\fB\-q\ \fR\fB\fIfilename\fR\fR] [\fB\-u\ \fR\fB\fIauth\fR\fR] [\fB\-xV\fR] [addr]
.SH "DESCRIPTION"
.PP

\fByaz\-client\fR
is a Z39.50/SRU client (origin) with a simple command line interface that allows you to test behavior and performance of Z39.50 targets and SRU servers.
.PP
If the
\fIaddr\fR
is specified, the client creates a connection to the Z39.50/SRU target at the address given.
.PP
When
\fByaz\-client\fR
is invoked it attemps to read the following files:
$HOME/.yazclientrc
(home directory, Unix only) and
.yazclientrc
(current directory \- any platform) For those files that are readable, the YAZ client executes commands in those files. See COMMANDS section for description of commands.
.SH "OPTIONS"
.PP
\-a \fIfilename\fR
.RS 3n
If specified, logging of protocol packages will be appended file given. If
\fIfilename\fR
is specified as
\-, the output is written to
stdout.
.RE
.PP
\-b \fIfilename\fR
.RS 3n
If specified, YAZ will dump BER data in readable notation to the file specified. If
\fIfilename\fR
is specified as
\-
the output is written to
stdout.
.RE
.PP
\-c \fIfilename\fR
.RS 3n
If specified, CCL configuration will be read from the file given.
.RE
.PP
\-d \fIdump\fR
.RS 3n
If specified, YAZ will dump BER data for all PDUs sent and received to individual files, named
\fIdump\fR.DDD.raw, where DDD is 001, 002, 003, ..
.RE
.PP
\-k \fIsize\fR
.RS 3n
Sets preferred messages and maximum record size for Initialize Request in kilobytes. Default value is 1024 (1 MB).
.RE
.PP
\-m \fIfilename\fR
.RS 3n
If specified, retrieved records will be appended to the file given.
.RE
.PP
\-p \fIaddr\fR
.RS 3n
If specified, the client will use the proxy at the address given.
.RE
.PP
\-q \fIfilename\fR
.RS 3n
If specified, CQL configuration will be read from the file given.
.RE
.PP
\-u \fIauth\fR
.RS 3n
If specified, the
\fIauth\fR
string will be used for authentication.
.RE
.PP
\-V
.RS 3n
Prints YAZ version.
.RE
.PP
\-x
.RS 3n
Makes the YAZ client print hex dumps of packages sent and received on standard output.
.RE
.SH "COMMANDS"
.PP
The YAZ client accepts the following commands.
.PP
open \fIzurl\fR
.RS 3n
Opens a connection to a server. The syntax for
\fIzurl\fR
is the same as described above for connecting from the command line.
.sp
Syntax:
.sp
[(tcp|ssl|unix|http)':']\fIhost\fR
[:\fIport\fR][/\fIbase\fR]
.RE
.PP
quit
.RS 3n
Quits YAZ client
.RE
.PP
find \fIquery\fR
.RS 3n
Sends a Search Request using the
\fIquery\fR
given. By default the query is assumed to be PQF. See command
querytype.
.RE
.PP
delete \fIsetname\fR
.RS 3n
Deletes result set with name
\fIsetname\fR
on the server.
.RE
.PP
base \fIbase1\fR \fIbase2\fR ...
.RS 3n
Sets the name(s) of the database(s) to search. One or more databases may be specified separated by blanks. This commands overrides the database given in
\fIzurl\fR.
.RE
.PP
show [\fIstart\fR[+\fInumber\fR]]
.RS 3n
Fetches records by sending a Present Request from the start position given by
\fIstart\fR
a number of records given by
\fInumber\fR. If
\fIstart\fR
is not given, then the client will fetch from position of the last retrieved record plus 1. If
\fInumber\fR
is not given, then one record will be fetched at a time.
.RE
.PP
scan \fIterm\fR
.RS 3n
Scans database index for a term. The syntax resembles the syntax for
find. If you want to scan for the word
water
you could write
.sp
.RS 3n
.nf
    scan water
   
.fi
.RE
but if you want to scan only in, say the title field, you would write
.sp
.RS 3n
.nf
    scan @attr 1=4 water
   
.fi
.RE
.RE
.PP
scanpos \fIpos\fR
.RS 3n
Sets preferred position for scan. This value is used in next scan. By default position is 1.
.RE
.PP
scansize \fIsize\fR
.RS 3n
Sets number of entries to be returned by scan. Default number of entries is 20.
.RE
.PP
scanstep \fIstep\fR
.RS 3n
Set step\-size for scan. This value is used in next scan sent to the target. By default step\-size is 0.
.RE
.PP
sort \fIsortspecs\fR
.RS 3n
Sorts a result set. The sort command takes a sequence of space\-separated sort specifications, with each sort specification consisting of two space\-separated words (so that the whole specification list is made up of an even number of words). The first word of each specification holds a field (sort criterion) and the second holds flags. If the sort criterion includes
=
it is assumed that the
SortKey
is of type
sortAttributes
using Bib\-1: in this case the integer before
=
is the attribute type and the integer following
=
is the attribute value. If no
=
is in the criterion it is treated as a sortfield of type InternationalString. The flags word of each sort specification must consist of
s
for case sensitive or
i
for case insensitive, and
<
for ascending order or
>
for descending order.
.RE
.PP
sort+
.RS 3n
Same as
sort
but stores the sorted result set in a new result set.
.RE
.PP
authentication \fIopenauth\fR
.RS 3n
Sets up a authentication string if a server requires authentication (v2 OpenStyle). The authentication string is first sent to the server when the
open
command is issued and the Z39.50 Initialize Request is sent, so this command must be used before
open
in order to be effective. A common convention for the
\fIauthopen\fR
string is that the username \- and password is separated by a slash, e.g.
myusername/mysecret.
.RE
.PP
sru \fImethod\fR
.RS 3n
Selects SRU method. Must be one of
POST,
GET,
SOAP
(default).
.RE
.PP
list_all
.RS 3n
This command displays status and values for many settings.
.RE
.PP
lslb \fIn\fR
.RS 3n
Sets the limit for when no records should be returned together with the search result. See the
[1]\&\fI Z39.50 standard \fR
for more details.
.RE
.PP
ssub \fIn\fR
.RS 3n
Sets the limit for when all records should be returned with the search result. See the
[1]\&\fI Z39.50 standard \fR
for more details.
.RE
.PP
mspn \fIn\fR
.RS 3n
Sets the number of records should be returned if the number of records in the result set is between the values of
lslb
and
ssub. See the
[1]\&\fI Z39.50 standard \fR
for more details.
.RE
.PP
status
.RS 3n
Displays the values of
lslb,
ssub
and
mspn.
.RE
.PP
setname
.RS 3n
Switches named result sets on and off. Default is on.
.RE
.PP
cancel
.RS 3n
Sends a Trigger Resource Control Request to the target.
.RE
.PP
format \fIoid\fR
.RS 3n
Sets the preferred transfer syntax for retrieved records. yaz\-client supports all the record syntaxes that currently are registered. See
[2]\&\fI Z39.50 Standard \fR
for more details. Commonly used records syntaxes include usmarc, sutrs, grs1 and xml.
.RE
.PP
elements \fIe\fR
.RS 3n
Sets the element set name for the records. Many targets support element sets are B (for brief) and F (for full).
.RE
.PP
close
.RS 3n
Sends a Z39.50 Close APDU and closes connection with the peer
.RE
.PP
querytype \fItype\fR
.RS 3n
Sets the query type as used by command
find. The following is supported:
prefix
for
Prefix Query Notation
(Type\-1 Query);
ccl
for CCL search (Type\-2 Query),
cql
for CQL (Type\-104 search with CQL OID),
ccl2rpn
for
CCL
to RPN conversion (Type\-1 Query).
cql2rpn
for CQL to RPN conversion (Type\-1 Query).
.RE
.PP
attributeset \fIset\fR
.RS 3n
Sets attribute set OID for prefix queries (RPN, Type\-1).
.RE
.PP
refid \fIid\fR
.RS 3n
Sets reference ID for Z39.50 Request(s).
.RE
.PP
itemorder \fItype\fR \fIno\fR
.RS 3n
Sends an Item Order Request using the ILL External.
\fItype\fR
is either 1 or 2 which corresponds to ILL\-Profile 1 and 2 respectively. The
\fIno\fR
is the Result Set position of the record to be ordered.
.RE
.PP
update \fIaction\fR \fIrecid\fR \fIdoc\fR
.RS 3n
Sends Item Update Request. The
\fIaction\fR
argument must be the action type: one of
insert,
replace,
delete
and
update. The second argument,
\fIrecid\fR, is the record identifier (any string). Third argument which is optional is the record document for the request. If doc is a quoted string (double quotes) the string content is used verbatim. If doc is not a quoted string, it is assumed to be a filename which is read, then sent as the docuemnt content. If doc is omitted, the last received record (as parf of present response or piggybacked search response) is used for the update.
.RE
.PP
. \fIfilename\fR
.RS 3n
Executes list of commands from file
\fIfilename\fR, just like source on most UNIX shells.
.RE
.PP
! \fIargs\fR
.RS 3n
Executes command
\fIargs\fR
in subshell using the
system
call.
.RE
.PP
push_command \fIcommand\fR
.RS 3n
The push_command takes another command as its argument. That command is then added to the history information (so you can retrieve it later). The command itself is not executed. This command only works if you have GNU readline/history enabled.
.RE
.PP
set_apdufile \fIfilename\fR
.RS 3n
Sets that APDU should be logged to file
\fIfilename\fR. Another way to achieve APDU log is by using command\-line option
\-a.
.RE
.PP
set_auto_reconnect \fIflag\fR
.RS 3n
Specifies whether YAZ client automatically reconnect if target closes connection (Z39.50 only).
.sp

\fIflag\fR
must be either
on
or
off.
.RE
.PP
set_auto_wait \fIflag\fR
.RS 3n
Specifies whether YAZ client should wait for response protocol packages after a request. By default YAZ client waits (on) for response packages immediately after a command (find, show) has been issued. If
off
is used, YAZ client does not attempt to receive packages automatically. These will have to be manually received when command
wait_response
is used.
.sp

\fIflag\fR
must be either
on
or
off.
.RE
.PP
set_marcdump \fIfilename\fR
.RS 3n
Specifies that all retrieved records should be appended to file
\fIfilename\fR. This command does the thing as option
\-m.
.RE
.PP
schema \fIschemaid\fR
.RS 3n
Specifies schema for retrieval. Schema may be specified as an OID for Z39.50. For SRU, schema is a simple string URI.
.RE
.PP
charset \fInegotiationcharset\fR [\fIdisplaycharset\fR] [[\fImarccharset\fR]]
.RS 3n
Specifies character set (encoding) for Z39.50 negotiation / SRU encoding and/or character set for output (terminal).
.sp

\fInegotiationcharset\fR
is the name of the character set to be negotiated by the server. The special name
\-
for
\fInegotiationcharset\fR
specifies
\fIno\fR
character set to be negotiated.
.sp
If
\fIdisplaycharset\fR
is given, it specifies name of the character set of the output (on the terminal on which YAZ client is running). To disable conversion of characters to the output encoding, the special name
\-
(dash) can be used. If the special name
auto
is given, YAZ client will convert strings to the encoding of the terminal as returned by
\fBnl_langinfo\fR
call.
.sp
If
\fImarcharset\fR
is given, it specifies name of the character set of retrieved MARC records from server. See also
marcharset
command.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBNote\fR
Since character set negotation takes effect in the Z39.50 Initialize Request you should issue this command before command
open
is used.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBNote\fR
MARC records are not covered by Z39.50 character set negotiation, so that's why there is a separate character that must be known in order to do meaningful converson(s).
.RE
.PP
negcharset \fIcharset\fR
.RS 3n
Specifies character set for negotiation (Z39.50). The argument is the same as second argument for command
charset.
.RE
.PP
displaycharset \fIcharset\fR
.RS 3n
Specifies character set for output (display). The argument is the same as second argument for command
charset.
.RE
.PP
marccharset \fIcharset\fR
.RS 3n
Specifies character set for retrieved MARC records so that YAZ client can display them in a character suitable for your display. See
charset
command. If
auto
is given, YAZ will assume that MARC21/USMARC is using MARC8/UTF8 and ISO\-8859\-1 for all other MARC variants. The charset argument is the same as third argument for command
charset.
.RE
.PP
set_cclfile \fIfilename\fR
.RS 3n
Specifies that CCL fields should be read from file file
\fIfilename\fR. This command does the thing as option
\-c.
.RE
.PP
set_cqlfile \fIfilename\fR
.RS 3n
Specifies that CQL fields should be read from file file
\fIfilename\fR. This command does the thing as option
\-q.
.RE
.PP
register_oid \fIname\fR \fIclass\fR \fIOID\fR
.RS 3n
This command allows you to register your own object identifier \- so that instead of entering a long dot\-notation you can use a short name instead. The
\fIname\fR
is your name for the OID,
\fIclass\fR
is the class, and
\fIOID\fR
is the raw OID in dot notation. Class is one
appctx,
absyn,
attet,
transyn,
diagset,
recsyn,
resform,
accform,
extserv,
userinfo,
elemspec,
varset,
schema,
tagset,
general. If you're in doubt use the
general
class.
.RE
.PP
register_tab \fIcommand\fR \fIstring\fR
.RS 3n
This command registers a TAB completion string for the command given.
.RE
.PP
sleep \fIseconds\fR
.RS 3n
This command makes YAZ client sleep (be idle) for the number of seconds given.
.RE
.PP
wait_response [ \fInumber\fR]
.RS 3n
This command makes YAZ client wait for a number of response packages from target. If
\fInumber\fR
is omitted, 1 is assumed.
.sp
This command is rarely used and is only useful if command
set_auto_wait
is set to off.
.RE
.PP
xmles \fIOID\fR \fIdoc\fR
.RS 3n
Sends XML Extended Services request using the OID and doc given.
.RE
.PP
zversion \fIver\fR
.RS 3n
This command sets Z39.50 version for negotiation. Should be used before
open. By default 3 (version 3) is used.
.RE
.PP
options \fIop1 op2..\fR
.RS 3n
This command sets Z39.50 options for negotiation. Should be used before
open.
.sp
The following options are supported:
search,
present,
delSet,
resourceReport,
triggerResourceCtrl,
resourceCtrl,
accessCtrl,
scan,
sort,
extendedServices,
level_1Segmentation,
level_2Segmentation,
concurrentOperations,
namedResultSets,
encapsulation,
resultCount,
negotiationModel,
duplicationDetection,
queryType104,
pQESCorrection,
stringSchema.
.RE
.SH "FILES"
.PP

\fIyaz\-<version>/client/client.c\fR
.PP

\fI.yazclientrc\fR
.PP

\fI$HOME/.yazclientrc\fR
.SH "SEE ALSO"
.PP

\fByaz\fR(7)
.PP
Section "The YAZ Client" in the YAZ manual.
.PP
Section "Prefix Query Format" in the YAZ manual.
.PP
Section "Common Command Language" in the YAZ manual.
.PP
Section "Common Query Language" in the YAZ manual.
.SH "REFERENCES"
.TP 3
1.\ Z39.50 standard
\%http://www.loc.gov/z3950/agency/markup/04.html#3.2.2.1.6
.TP 3
2.\ Z39.50 Standard
\%http://www.loc.gov/z3950/agency/defns/oids.html#5
