.\"     Title: yaz
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 12/17/2006
.\"    Manual: 
.\"    Source: YAZ 2.1.42
.\"
.TH "YAZ" "7" "12/17/2006" "YAZ 2.1.42" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
yaz \- Z39.50 toolkit.
.SH "SYNOPSIS"
.HP 4
\fBYAZ\fR
.SH "DESCRIPTION"
.PP
YAZ is a C/C++ programmer's toolkit supporting the development of Z39.50v3 clients and servers. The YAZ toolkit offers several different levels of access to the ISO23950/Z39.50, SRU and ILL protocols. The level that you need to use depends on your requirements, and the role (server of client) that you want to implement.
.SH "COPYRIGHT"
.PP
Copyright \(co 1995\-2006 Index Data.
.PP
All rights reserved.
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.TP 3n
\(bu
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
.TP 3n
\(bu
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
.TP 3n
\(bu
Neither the name of Index Data nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
.PP
THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.SH "SEE ALSO"
.PP

\fByaz\-client\fR(1),
\fByaz\-ztest\fR(8),
\fByaz\-config\fR(8),
\fBzoomsh\fR(1)
.PP
YAZ manual (
\fI/usr/local/share/doc/yaz\fR)
.PP

[1]\&\fIYAZ home page\fR.
.PP

[2]\&\fIZ39.50 Maintenance Agency Page\fR.
.SH "REFERENCES"
.TP 3
1.\ YAZ home page
\%http://www.indexdata.com/yaz/
.TP 3
2.\ Z39.50 Maintenance Agency Page
\%http://www.loc.gov/z3950/agency/
