\input texinfo @c -*-texinfo-*-
@c This is the manual for Skim.

@c ======================================================================================
@c Localization Notes
@c ======================================================================================
@c 
@c Localization starts after "The content of the Help Pages starts here...".
@c Command names start with '@' and should not be localized.
@c Lines starting with @c, such as this one, are comments and should not be localized.
@c Arguments are written on the line after the command, or as a comma-separated list within braces. 
@c Most arguments should be localized, but not for @end or @box.
@c References (first argument of @ref or @xref, or between * and :: in a @menu) should be exactly the same as their target (argument of @node, @anchor, or @tpoic). 

@c ======================================================================================
@c Document info
@c ======================================================================================
@c
@setfilename skim.info

@setchapternewpage odd
@footnotestyle separate
@ifset shorttitlepage-enabled
@shorttitlepage Skim v@value{VERSION}
@end ifset

@c ======================================================================================
@c Macro definitions
@c ======================================================================================

@c macros for keyboard shortcuts

@macro cmd {key}
@html
&#8984;\key\
@end html
@ifnothtml
Cmd-\key\
@end ifnothtml
@end macro

@macro opt {key}
@html
&#8997;\key\
@end html
@ifnothtml
Opt-\key\
@end ifnothtml
@end macro

@macro shiftcmd {key}
@html
&#8679;&#8984;\key\
@end html
@ifnothtml
Shift-Cmd-\key\
@end ifnothtml
@end macro

@macro optcmd {key}
@html
&#8997;&#8984;\key\
@end html
@ifnothtml
Option-Cmd-\key\
@end ifnothtml
@end macro

@macro ctrcmd {key}
@html
&#8963;&#8984;\key\
@end html
@ifnothtml
Control-Cmd-\key\
@end ifnothtml
@end macro

@c A macro for search-result abstracts

@macro abstract{text}
@html
<META NAME="DESCRIPTION" CONTENT="\text\">
@end html
@end macro

@c Macros for special boxes

@macro box{class}
@html
<div class="\class\">
@end html
@end macro

@macro endbox
@html
</div>
@end html
@end macro

@macro topic{title}
@node \title\
@chapter \title\
@cindex \title\
@abstract{\title\}
@end macro

@c ======================================================================================
@c The content of the Help Pages starts here...
@c ======================================================================================

@documentlanguage en
@documentencoding UTF-8

@settitle Skim Help

@c DO NOT LOCALIZE THE NEXT LINE
@node Top
@c THIS SHOULD CORRESPOND TO CFBundleHelpBookFolder IN Infoplist.strings OR Info.plist
@top Skim Help

@box{topframe}

@box{topframeleft}

@heading @image{gfx/Skim,,, Skim} Skim Help

@image{gfx/screenshot,,, Screenshot}

@endbox

@box{topframeright}

Skim is a viewer for Portable Document Format (PDF) files, intended for easy reading and studying PDF documents.

You can search PDF files, bookmark them, add notes, highlight sections, and take "snapshot" for easy reference. Skim can also open PostScript (PS) files, converting them to PDF. 

In addition, with Skim you can fully concentrate  on reading the PDF file in a powerfull full screen mode, or give full screen presentations of your PDF file. 

@menu
* indexcp::
* More information::
@end menu

@endbox

@endbox

@c ======================================================================================

@topic Viewing PDF files

Skim can be used to open and print documents in Portable Document Format (PDF). A PDF file has elements of a printed document. Many PDF files are converted from printed documents, or created from the same source files as printed documents.

PDF files opened in Skim can be read, resized for onscreen viewing, and printed. You can search a PDF document for specific text, navigate some PDF files using a table of contents, select and copy text in the file, add notes and highlights, and give presentations.

If you open a PostScript (PS) or EPS file in Skim, it is converted to a PDF file.

@box{taskbox}
@heading To open all PDF documents in Skim:
@enumerate
@item In the Finder, select a PDF document.
@item Choose File > Get Info.
@item Click Open with:.
@item Choose Skim from the pop-up menu, and click Change All.
@end enumerate
@endbox

@c ======================================================================================

@topic Zooming in and out

You can change your view of a page in a PDF file in several ways. 

@box{taskbox}
@itemize
@item To zoom in or out, choose PDF > Zoom In or PDF > Zoom Out.
@end itemize
@itemize
@item To see the page in its original size, choose PDF > Actual Size.
@end itemize
@itemize
@item To view the PDF so that its pages fit in its window, choose PDF > Zoom To Fit.
@end itemize
@itemize
@item To keep the PDF so that its pages always fit in its window, also if you resize the window, choose PDF > Automatically Resize.
@end itemize
@itemize
@item To zoom to a particular section of a PDF document, choose Tools > Select Tool and select the section, then choose PDF > Zoom To Selection.
@end itemize
@itemize
@item To view a page at a size you specify, resize the window to the size you want, then choose PDF > Size To Fit. The page resizes to fit the window size.
@end itemize
@itemize
@item To see a page at a specific percentage of its original size, type a percentage in the Scale field in the toolbar. If you don't see the Scale field, choose View > Customize Toolbar.
@end itemize
@endbox

You can also use toolbar buttons to zoom. To add zoom buttons to the toolbar, choose View > Customize Toolbar and drag the buttons to the toolbar.

You can also use the contextual menu to zoom.

If your mouse or other input device has a scroll wheel, you can also zoom by holding the Option key and moving the scroll wheel.

You cannot save changes to the way you view a page.

@heading See also
@menu
* Resizing the window to fit its contents::
* Setting the default view options for a PDF document::
@end menu

@c ======================================================================================

@topic Magnifying a section of a PDF document

You can live-magnify a section of the PDF file, for example to better view small text.

@box{taskbox}
@heading To magnify a section:
@enumerate
@item Choose Tools > Magnify Tool.
@item Press the left mouse button while moving over the section you want to magnify.
@end enumerate
@heading To modify the magnification:
@itemize
@item Hold the Apple key for extra magnification.
@item Hold the Option key and/or double-click to magnify a larger area.
@item Hold the Shift key to zoom out (invert the magnification).
@end itemize
@endbox

@c ======================================================================================

@topic Selecting the page to view in a PDF document

When you open a PDF document with multiple pages, a single Skim window opens showing the first page of the document. You can see thumbnails of additional pages in the Contents pane on the left.

@box{taskbox}
@itemize
@item To open the left side pane (if it isn't already open), choose View > Show Contents pane, or double-click the divider on the left of the PDF.
@end itemize
@itemize
@item If a PDF has a table of contents (TOC), a TOC icon appears at the top of the left side pane. Click the icon to use the TOC to navigate the PDF.
@end itemize
@itemize
@item To navigate using thumbnail images of the document's pages, click the Thumbnails icon in the contents pane and click the thumbnail image for the page.
@end itemize
@itemize
@item To jump to the next page, press the Down Arrow or Page Down key. To jump to the previous page, press the Up Arrow or Page Up key.
@end itemize
@itemize
@item To use the vertical scroll bar to scroll through a PDF with several pages, choose PDF > PDF Display > Single Page Continuous or PDF > PDF Display > Two Pages Continuous.
@end itemize
@itemize
@item To view a specific page in a PDF document, type the page number that you want to view in the Page Number field in the toolbar, then press Return.
@end itemize
@endbox

By default, the contents pane always opens automatically. However you can choose to open the contents pane automatically only when the PDF file has a table of contents. To set the contents pane to open automatically only if there is a table of contents, choose Skim > Preferences, click General, and select "Open pane only for Table of Contents."

@heading See also
@menu
* Viewing the table of contents for a PDF file::
* Scrolling PDF pages::
@end menu

@c ======================================================================================

@topic Scrolling PDF pages

When you open a PDF file with multiple pages in Skim, you select the page you want to view by clicking it in the contents pane. If the page does not fit within the window size, then you use the vertical or horizontal scroll bars to view the hidden parts of the current page.

By default, you can't use the vertical scroll bar to view the next or previous pages of the document. However, you can change this by turning on continuous scrolling.

You can also scroll pages by dragging with the mouse.

@box{taskbox}
@heading To use the vertical scroll bar to scroll through the pages of the document:
@itemize
@item Choose PDF > PDF Display > Single Page Continuous or PDF > PDF Display > Two Pages Continuous.
@end itemize
@heading To scroll by dragging:
@itemize
@item Choose Tools > Scroll Tool.
@end itemize
@endbox

@heading See also
@menu
* Selecting the page to view in a PDF document::
* Viewing page breaks::
* Setting the default view options for a PDF document::
@end menu

@c ======================================================================================

@topic Changing the background color

By default, Skim shows a gray background behind images and PDF files, and a darker shade of gray in Full Screen mode. If you expand the window larger than the size of the document, or if the image has transparent sections, you can see the background color.

@box{taskbox}
@itemize
@item To change the default background color, choose Skim > Preferences, click Display, and then click Normal below "Background color".
@end itemize
@itemize
@item To change the background color for Full Screen mode, choose Skim > Preferences, click Display, and then click "Full Screen" below "Background color".
@end itemize
@endbox

@heading See also
@menu
* Viewing PDF documents in full screen::
@end menu

@c ======================================================================================

@topic Finding text in a PDF file

You can search a PDF file for a word or any set of characters.

@box{taskbox}
@heading To find all occurrences of text:
@enumerate
@item Open the PDF file. If the Contents pane isn't open, choose View > Show Contents Pane.
@item Type some text in the search field and press Return. A list of places where the text occurs appears in the contents pane.
@item Click an occurrence of the text in the Contents pane. Skim shows the page where the text occurs, and highlights the text.
@end enumerate
@heading To find a single occurrences of text:
@enumerate
@item Choose Edit > Find > Find@dots{}, to show a Find panel.
@item Type some text in the search field, and press Enter or hit Next. 
@end enumerate
@endbox

@heading See also
@menu
* Changing the highlighting of Find results::
@end menu

@c ======================================================================================

@topic Selecting and copying text in a PDF file

You can select and copy text from a PDF file, then paste it into another application, such as a word processor.

@box{taskbox}
@itemize
@item To copy text, choose Tools > Text Tool and drag over the text as you normally would. Then choose Edit > Copy. With some PDF files, line breaks are not saved when you copy text, so when you paste the text, the lines all run together.
@item To select only a portion of text horizontally (for example, to select only one column in a two-column document), choose Tools > Text Tool, then press the Option key and select the text.
@end itemize
@endbox

@heading See also
@menu
* Pasting notes in a PDF file::
@end menu

@c ======================================================================================

@topic Copying notes in a PDF file

You can select and copy notes from a PDF file, then paste it into the same or another PDF document. Notes that can be copied are text notes, anchored notes, circle highlights and box highlights. 

@box{taskbox}
@itemize
@item To copy a note, choose Tools > Text Tool and select a note. Then choose Edit > Copy.
@end itemize
@endbox

You can also create a dublicate of a note by selecting the note while holding the Option key. 

@heading See also
@menu
* Pasting notes in a PDF file::
* Selecting and copying text in a PDF file::
@end menu

@c ======================================================================================

@topic Pasting notes in a PDF file

You can paste a note you have copied from a PDF file into the same or another PDF document. Notes that can be copied are text notes, anchored notes, circle highlights and box highlights. 

You can also paste copied text to create a new text or anchored note. 

@box{taskbox}
@itemize
@item To paste a copied note, choose Edit > Paste after copying a note.
@end itemize
@itemize
@item To paste copied text as a new text note, choose Edit > Paste after copying text.
@end itemize
@itemize
@item To paste copied text as a anchored text note, hold down the Option key, and choose Edit > Paste after copying text.
@end itemize
@endbox

@heading See also
@menu
* Copying notes in a PDF file::
* Selecting and copying text in a PDF file::
@end menu

@c ======================================================================================

@topic Rotating a PDF file or page

In Skim, you can rotate a PDF file in 90-degree increments. You can rotate and flip an image several times to orient it the way you want it. 

@box{taskbox}
@itemize
@item To turn all the pages in a PDF file 90 degrees in either direction, choose Tools > Rotate Left or Tools > Rotate Right.
@end itemize
@itemize
@item To turn only the currently viewed page  90 degrees in either direction, choose Tools > Rotate Page Left or Tools > Rotate Page Right.
@end itemize
@endbox

You can also use toolbar buttons to rotate images. To add rotate buttons to the toolbar, choose View > Customize Toolbar and drag the buttons to the toolbar.

@c ======================================================================================

@topic Cropping pages of a PDF document

You can crop a page in a PDF document to remove parts you don't need. You can crop just the page you are viewing or all pages in the document.

@box{taskbox}
@heading To crop the current page:
@enumerate
@item If you want to choose a custom size, choose Tools > Select Tool, and select the portion of the page you want to keep, or choose Tools > Select Content to set the selection to the content of the current page.
@item Choose Tools > Crop Page. Without a selection, the content of the page will be automatically determined.
@end enumerate
@heading To crop all pages:
@enumerate
@item If you want to choose a custom size, choose Tools > Select Tool, and select the portion of the page you want to keep, or choose Tools > Select Content to extend the selection to contain the content of the current page.
@item Choose Tools > Crop. Without selection, the content of the pages will be automatically determined.
@end enumerate
@heading To crop all pages to their individual content:
@itemize
@item Hold down the Shift key, and choose Tools > Auto Crop. This can be useful for unevenly scanned articles.
@end itemize
@heading To crop all pages automatically to a common size:
@itemize
@item Hold down the Control key, and choose Tools > Auto Crop. This can be useful for unevenly scanned articles that still have pages of approximately the same size.
@end itemize
@endbox

Cropping a document does not destroy any of its contents. You can always view the uncropped document by choosing PDF > PDF Display > Media Box. To view the cropped document, choose PDF > PDF Display > Crop Box. 

@c ======================================================================================

@topic Viewing the table of contents for a PDF file

Some PDF files contain a table of contents, which lets you quickly jump to sections within a document.

@box{taskbox}
@itemize
@item To view the table of contents, Choose View > Show Contents Pane, and click the TOC button or choose View > Table Of Contents.
@end itemize
@itemize
@item To jump to a specific section, click its name in the contents pane. 
@end itemize
@endbox

@heading See also
@menu
* Selecting the page to view in a PDF document::
@end menu

@c ======================================================================================

@topic Setting the default view options for a PDF document

You can choose the PDF display options at which Skim displays new PDF documents. These view options include all the settings in the PDF > PDF Display submenu, the default document scale, and wether the document automatically scales with its window allows.

@box{taskbox}
@itemize
@item To save the current display options of a document as the default to use for newly opened documents, select PDF > Use Current View Settings as Default.
@end itemize
@itemize
@item To revert the initial display settings to their original default values, choose Skim > Preferences, choose General, and press the button below 'Revert initial PDF view settings for:'.
@end itemize
@endbox

By default, full screen mode uses the same view settings as normal mode. You can however also use separate PDF display options for full screen mode. Simply follow the instructions above while you are in full screen mode. To see the menu bar, move the mouse to the top of the screen. 

@heading See also
@menu
* Viewing pages side-by-side::
* Viewing page breaks::
* Scrolling PDF pages::
* Zooming in and out::
@end menu

@c ======================================================================================

@topic Viewing pages side-by-side

Viewing pages side-by-side lets you display more of a document on the screen.

@box{taskbox}
@itemize
@item To view two pages side-by-side, choose PDF > PDF Display > Two Pages or PDF > PDF Display > Two Pages Continuous. If you want the first page to be a right-hand page, as it would be in a book, choose PDF > PDF Display > Book Mode. Otherwise, the first page will be a left-hand page. 
@end itemize
@itemize
@item To stop viewing pages side-by-side, choose PDF > PDF Display > Single Page or PDF > PDF Display > Single Page Continuous.
@end itemize
@endbox

@heading See also
@menu
* Viewing page breaks::
* Setting the default view options for a PDF document::
@end menu

@c ======================================================================================

@topic Viewing page breaks

When you're viewing more than one PDF page at a time, it can be difficult to tell when one ends and another begins. Displaying a border around each page makes this easier. 

@box{taskbox}
@itemize
@item To display a border around each page, Choose PDF > PDF Display > Page Breaks.
@end itemize
@endbox

@heading See also
@menu
* Viewing pages side-by-side::
* Scrolling PDF pages::
* Setting the default view options for a PDF document::
@end menu

@c ======================================================================================

@topic Adding notes to a PDF document

You can add your notes to a PDF document in boxes that look like paper sticky notes, or more extensive anchored notes that can be viewed in a separate window by double-clicking. 

The notes are saved with the document, so also other Skim users can see them. The notes are not saved in the PDF data itself, therefore other PDF viewers will probably not be able to show the notes. 

@box{taskbox}
@heading To add a text note:
@enumerate
@item Choose Tools > Text Tool. 
@item Choose Notes > Text Note. 
@item Drag in the document until the note is located where you want and has the size you want.
@item To enter text, double-click the note. 
@end enumerate
@heading or:
@enumerate
@item Choose Tools > Note Type > Text Note.
@item Select region for the text note, and enter the text. You can do this repeatedly.
@end enumerate
@heading To add a longer text note:
@enumerate
@item Choose Tools > Text Tool. 
@item Choose Notes > Anchored Note. 
@item Drag in the document until the note is located where you want.
@item To enter text, double-click the note. A window will show containing the text of the note. It has a short text that is used for identification, and a longer text that can also contain attributes. 
@item You can also add a simple image to the note. Drag an image to the image well in the window for the note. 
@end enumerate
@heading or:
@enumerate
@item Choose Tools > Note Type > Anchored Note.
@item Click at the point where you want to put the new note. You can do this repeatedly.
@end enumerate
@endbox

You can also use toolbar buttons to add notes. To add notes buttons to the toolbar, choose View > Customize Toolbar and drag the buttons to the toolbar.

You can edit or delete the notes. To move or resize the note, choose Tools > Text Tool or Tools > Note Tool, and use the mouse.  Drag the black box to resize. To edit the note's text, choose Tools > Text Tool or Tools > Note Tool, and double-click the note. To change the color used for the note, choose Tools > Show Colors. To delete the note, choose Tools > Text Tool, select the note, and press Delete.

@heading See also
@menu
* Highlighting sections of a PDF document::
* Adding lines to a PDF document::
* Changing the color for notes and highlights::
* Changing the font of text notes::
* Changing the line or border style for notes::
@end menu

@c ======================================================================================

@topic Highlighting sections of a PDF document

You can highlight interesting or important parts of a document. You can enclosing them in a red oval or a green box. Or you can highlight, underline or strike out text.

The highlights are saved with the document, so also other Skim users can see them. The highlights are not saved in the PDF data itself, therefore other PDF viewers will probably not be able to show the highlights. 

@box{taskbox}
@heading To highlight a section of a PDF document:
@enumerate
@item Choose Tools > Text Tool. 
@item Select the text you want to highlight.
@item Choose Notes > Circle, Notes > Box, Notes > Highlight, Notes > Underline, or Notes > Strike Out. 
@item You may drag circle and box highlights in the document until the highlight is located where you want and has the size you want.
@end enumerate
@heading or:
@enumerate
@item Choose Tools > Note Type > Circle, Tools > Note Type > Box, Tools > Note Type > Highlight, Tools > Note Type > Underline, or Tools > Note Type > Strike Out. 
@item Select the text you want to highlight or region you want to circle. You can do this repeatedly.
@end enumerate
@endbox

You can also use toolbar buttons to add highlights. To add highlight buttons to the toolbar, choose View > Customize Toolbar and drag the buttons to the toolbar.

You can edit or delete the highlights. To change the color used for the highlight, choose Tools > Show Colors. To delete the highlight, choose Tools > Text Tool or Tools > Note Tool, select the highlight, and press Delete. 

Circle and box highlights can also be moved and resized. To move or resize the highlight, choose Tools > Text Tool or Tools > Note Tool, and use the mouse. Drag the black box to resize. 

@heading See also
@menu
* Adding notes to a PDF document::
* Adding lines to a PDF document::
* Changing the color for notes and highlights::
@end menu

@c ======================================================================================

@topic Adding lines to a PDF document

You can add lines to a PDF document, to highlight relations between sections. 

The lines are saved with the document, so also other Skim users can see them. The lines are not saved in the PDF data itself, therefore other PDF viewers will probably not be able to show the lines. 

@box{taskbox}
@heading To add a line:
@enumerate
@item Choose Tools > Text Tool. 
@item Choose Notes > Line. 
@item Drag in the document until the line is located where you want, and drag the end points until it points where you want.
@end enumerate
@heading or:
@enumerate
@item Choose Tools > Note Type > Line.
@item Stroke the line using the mouse from the start point to the end point. You can do this repeatedly.
@end enumerate
@heading To add a freehand line:
@enumerate
@item Choose Tools > Note Type > Freehand.
@item Stroke the line using the mouse. You can do this repeatedly.
@end enumerate
@endbox

You can also use toolbar buttons to add lines. To add a line button to the toolbar, choose View > Customize Toolbar and drag the button to the toolbar.

You can edit or delete the line. To move the line or its end points, choose Tools > Text Tool or Tools > Note Tool, and use the mouse. Drag a black box to move an end point. To change the color used for the line, choose Tools > Show Colors. To delete the line, choose Tools > Text Tool or Tools > Note Tool, select the line, and press Delete.

@heading See also
@menu
* Adding notes to a PDF document::
* Highlighting sections of a PDF document::
* Changing the color for notes and highlights::
* Changing the line or border style for notes::
@end menu

@c ======================================================================================

@topic Changing the color for notes and highlights

Skim allows you to change the color of a note, highlight or line you have added using Skim. You can also change the default colors that are used for new notes, highlights and lines.

@box{taskbox}
@heading To change the default color for notes, highlights and lines:
@itemize
@item Choose Skim > Preferences, select Notes, and click a color for the type of note, highlight or line you want to change.
@end itemize
@heading To change the color of a single note, highlight or line:
@itemize
@item Select the note, highlight or line in the PDF and choose Tools > Show Colors.
@end itemize
@endbox

@heading See also
@menu
* Adding notes to a PDF document::
* Highlighting sections of a PDF document::
* Adding lines to a PDF document::
* Changing the font of text notes::
@end menu

@c ======================================================================================

@topic Changing the font of text notes

Skim allows you to change the font of a text note you have added using Skim. You can also change the default font that are used for new text notes.

@box{taskbox}
@heading To change the default font for text notes:
@itemize
@item Choose Skim > Preferences, select Notes, and select a font name and size below 'Text note font'.
@end itemize
@heading To change the font of a single text note:
@itemize
@item Select the note in the PDF and choose View > Font > Show Fonts.
@end itemize
@endbox

@heading See also
@menu
* Adding notes to a PDF document::
* Highlighting sections of a PDF document::
* Adding lines to a PDF document::
* Changing the color for notes and highlights::
* Changing the line or border style for notes::
@end menu

@c ======================================================================================

@topic Changing the line or border style for notes

Skim allows you can change the border style of a note or the line style of a line you have added using Skim. You can also change the default line styles that are used for new notes and lines.

@box{taskbox}
@heading To change the default border or line style for notes and lines:
@itemize
@item Choose Skim > Preferences, select Notes, and click a line style control for the type of note or line you want to change.
@end itemize
@heading To change the border or line style of a single note, highlight or line:
@itemize
@item Select the note or line in the PDF and choose Tools > Show Lines.
@end itemize
@endbox

When you have a line style control or a note selected, you change the line styles in the Lines panel. You can change the line width, the style of the lines, and the dash pattern. To get a dashed line, select the dashed line style and type in the lengths for the dash pattern. For lines you can also change the head and tail style.

@heading See also
@menu
* Adding notes to a PDF document::
* Adding lines to a PDF document::
* Changing the color for notes and highlights::
* Changing the font of text notes::
@end menu

@c ======================================================================================

@topic Taking snapshots of a section of a PDF document

You can take "snapshots" of important sections of a PDF document, to keep them on your screen for easy reference. This way you don't have to leaf back to the section every time you want to see it. 

Your snapshots are kept for easy reference in a table in the Notes pane to the right of the PDF document. 

@box{taskbox}
@heading To take a snapshot of a section:
@enumerate
@item Choose Tools > Text Tool or Tools > Scroll Tool.
@item Hold the Apple key and click on point or select a region.
@item A window will pop up displaying the chosen region. If the selected region is small, this will be magnified. 
@end enumerate
@heading To see all your snapshots:
@enumerate
@item Choose View > Show Notes Pane, or double-click the divider on the right, if necessary.
@item Choose View > Snapshots.
@end enumerate
@endbox

You can minimize the window to leave it only in the table. Choose Window > Minimize, hit the Minimize button on the snapshot window, or double-click the item in the Snapshots table.

You can later show the snapshot window again by double-clicking the snapshot in the Snapshot table. 

Snapshots are not saved with the PDF document. 

@c ======================================================================================

@topic Keeping snapshot windows on top

By default, snapshot windows are at the same level as any other normal windows. Therefore, if you select the main windows, the snapshot windows may be hidden behind it. Skim allows you to keep all your snapshot windows on top of the main window, so they are always visible. 

@box{taskbox}
@itemize
@item To keep snapshot windows on top, choose Skim > Preferences, click General, and select "Keep snapshot windows on top".
@end itemize
@endbox

In full screen mode, snapshot windows are always on top. 

@c ======================================================================================

@topic Keeping anchored note windows on top

By default, note windows for anchored notes are at the same level as any other normal windows. Therefore, if you select the main windows, the note windows may be hidden behind it. Skim allows you to keep note windows on top of the main window, so they are always visible. 

@box{taskbox}
@itemize
@item To keep a note window on top, select "Keep on top" at the bottom of the window.
@end itemize
@endbox

@c ======================================================================================

@topic Adding a bookmark to a PDF document

You can bookmark a page in a PDF document so you can quickly return to it, much like a web browser's bookmarks.

@box{taskbox}
@itemize
@item To add a bookmark for a file, choose Bookmarks > Add Bookmark, and enter a name.
@item To add a bookmark for the current session, choose Bookmarks > Add Session Bookmark, and enter a name.
@item To rename a bookmark, choose Bookmarks > Edit Bookmarks, and double-click its name.
@item To delete a bookmark, choose Bookmarks > Edit Bookmarks, select it, and click Remove.
@item To go to a bookmark, choose its name from the Bookmarks menu.
@end itemize
@endbox

@c ======================================================================================

@topic I can't select or copy text in a PDF file

Some PDF files require you to enter a password before you can select or copy text. Ask the person who gave you the document for that password.

@box{taskbox}
@itemize
@item To enter the password for a PDF file, choose File > Password.
@end itemize
@endbox

If the Password command is disabled, this document does not require you to enter one. Make sure you've selected the Text tool by choosing Tools > Text. If you still cannot select text, the PDF is probably a scanned PDF, which does not contain any text but rather an image that may look like text.

@c ======================================================================================

@topic I don't see line art in my PDF document

When you view a PDF file in Skim, some line art images may disappear if anti-aliasing is turned on.

@box{taskbox}
@heading To turn anti-aliasing on or off:
@enumerate
@item Choose Skim > Preferences, and click Display.
@item Select or deselect the "Anti-alias text and line art" checkbox.
@end enumerate
@endbox

@heading See also
@menu
* The text looks jagged in my PDF document::
* Small text is unreadable in my PDF document::
* Text in a PDF appears slowly::
@end menu

@c ======================================================================================

@topic The text looks jagged in my PDF document

When viewing a PDF file in Skim, larger text may look jagged. You can turn on anti-aliasing in Skim to make PDF files more readable.

@box{taskbox}
@heading To turn on anti-aliasing:
@enumerate
@item Choose Skim > Preferences, and click Display.
@item Select the "Anti-alias text and line art" checkbox.
@end enumerate
@endbox

If you turn on the "Anti-alias text and line art" option, large characters and line art are smoothed out and do not appear to be so jagged. Skim may take longer to display your document when smoothing out characters and line art.

@heading See also
@menu
* I don't see line art in my PDF document::
* Small text is unreadable in my PDF document::
* Text in a PDF appears slowly::
@end menu

@c ======================================================================================

@topic Small text is unreadable in my PDF document

When you view a PDF file in Skim, small text may look fuzzy or illegible. You can change a few options to make the text more legible.

@box{taskbox}
@heading To make small text more readable:
@enumerate
@item Choose Skim > Preferences, and click Display.
@item Deselect the "Anti-alias text and line art" checkbox.
@item Enter a smaller number in the "Greeking threshold" field.
@end enumerate
@endbox

Text in a point size smaller than the greeking threshold appears as a gray blur. The blurred text fits the outline of what the text would actually look like, but is illegible. Displaying blurred text takes less time because Skim doesn't need to render each character individually.

If you turn off the "Anti-alias text and line art" option, large characters and line art may appear jagged instead of smooth. Smoothing out the characters and art takes more time.

@heading See also
@menu
* I don't see line art in my PDF document::
* The text looks jagged in my PDF document::
* Text in a PDF appears slowly::
@end menu

@c ======================================================================================

@topic Text in a PDF appears slowly

If the text in a PDF document takes a long time to appear, you can change a few options to help speed it up.

@box{taskbox}
@heading To speed up the appearance of text:
@enumerate
@item Choose Skim > Preferences, and click Display.
@item Enter a larger number in the "Greeking threshold" field.
@item Deselect the "Anti-alias text and line art" checkbox.
@end enumerate
@endbox

Text in a point size smaller than the greeking threshold appears as a gray blur. The blurred text fits the outline of what the text would actually look like, but is illegible. Legible text may take longer to display because Skim must render each character individually.

If you turn off the "Anti-alias text and line art" option, small characters may appear fuzzy, and large characters and line art may appear jagged instead of smooth.

@heading See also
@menu
* I don't see line art in my PDF document::
* The text looks jagged in my PDF document::
* Small text is unreadable in my PDF document::
@end menu

@c ======================================================================================

@topic Resizing the window to fit its contents

When the PDF file is not set to zoom to fit its window, you can resize the window to fit around the PDF file and the side panes. 

@box{taskbox}
@itemize
@item To resize a window so that it fits around the PDF file, choose Window > Fit to PDF. 
@end itemize
@endbox

@heading See also
@menu
* Zooming in and out::
@end menu

@c ======================================================================================

@topic Showing the reading bar

In skim you can highlight the line of text you are reading, to help you concentrate on reading or easily find back what you were reading. 

@box{taskbox}
@itemize
@item To show the reading bar, choose View > Show Reading Bar.
@end itemize
@itemize
@item To move the reading bar to the next (previous) line, hold down the Option key and press the Down Arrow (Up Arrow) key.
@end itemize
@itemize
@item To move the reading bar to the next (previous) page, hold down the Option key and press the Right Arrow (Left Arrow) key.
@end itemize
@endbox
@itemize
@item To increase (decrease) the number of lines the reading bar spans, hold down the Option and Shift keys and press the Down Arrow (Up Arrow) key.
@end itemize
@endbox

You can also drag the reading bar to another line.

@heading See also
@menu
* Changing the color of the reading bar::
@end menu

@c ======================================================================================

@topic Changing the color of the reading bar

In skim you can highlight the line of text you are reading. You can change the color and transparency 

@box{taskbox}
@itemize
@item To change the color or transparency of the reading bar, choose Skim > Preferences, click Display, and select Color below "Reading bar". 
@end itemize
@endbox

You can also choose whether the reading bar should highlight just the current line, or mask all the other text. Select or deselect "Invert bar" in the preferences. 

@heading See also
@menu
* Showing the reading bar::
@end menu

@c ======================================================================================

@topic Viewing PDF documents in full screen

Skim allows you to view PDF documents in kiosk mode, so you can concentrate just on reading. 

@box{taskbox}
@itemize
@item To view a PDF document in kiosk mode, Choose View > Full Screen. 
@end itemize
@endbox

In full screen mode, you can still do all the task you can do in normal mode. 

The main menu auto-hides, and can be shown by moving the mouse to the top of the screen. Many options are also available in the context menu.

The contents tables and the notes and snapshot tables automatically show if you move the mouse to the side of the screen. You can also show them by choosing View > Show Contents Pane or View > Show Notes Pane. 

@heading See also
@menu
* Giving a presentation of a PDF document::
* Changing the background color::
@end menu

@c ======================================================================================

@topic Giving a presentation of a PDF document

You can also use Skim to give presentations of a PDF document. 

@box{taskbox}
@heading To show a presentation of a PDF document:
@enumerate
@item Drag the window of the PDF document to the screen you want to use for the presentation, likely a beamer. 
@item Choose View > Presentation. 
@item To get out of Presentation mode by the shortcut @optcmd{F}, or by hitting the escape button. 
@end enumerate
@endbox

In presentation mode, you can use the Left and Right Line buttons to navigate through the pages of the document. 

You can show navigation buttons by moving the mouse to the bottom of the screen.

@heading See also
@menu
* Viewing PDF documents in full screen::
@end menu

@c ======================================================================================

@topic Changing the size of the thumbnails

Skim allows you to change the size of thumbnails for pages and for snapshots.

@box{taskbox}
@itemize
@item To change the size of for page thumbnails, choose Skim > Preferences, click Display, and move the Pages slider.
@end itemize
@itemize
@item To change the size of for snapshot thumbnails, choose Skim > Preferences, click Display, and move the Snapshots slider.
@end itemize
@endbox

If you select the "Discrete sizes" button, you can restrict the sizes to certain discrete sizes. This may lead to sharper thumbnails. 

@c ======================================================================================

@topic Changing the highlighting of Find results

You can set whether Skim should circle highlight results of a text searches well as the color used for these highlights.

@box{taskbox}
@itemize
@item To highlight Find results using a circle, choose Skim > Preferences, click Display, and select "Highlight search results with color".
@item To change the color used for the Find highlights, click the color.
@end itemize
@endbox

@heading See also
@menu
* Finding text in a PDF file::
@end menu

@c ======================================================================================

@topic Automatically update files for external updates

Skim can automatically reload files you view when their contents changes on disk, by another program. 

@box{taskbox}
@itemize
@item To reload files when their contents changes on disk, choose Skim > Preferences, click Sync, and select "Check for file changes".
@end itemize
@endbox

Skim will always first ask you whether it should reload the file when the contents changes on disk, unless you have chosen Auto. 

@c ======================================================================================

@topic Check for updates of Skim

Skim can automatically check whether an update for Skim is available. You can also choose how often Skim checks for updates.  

@box{taskbox}
@itemize
@item To select how often Skim checks for updates, choose Skim > Preferences, click General, and select a period after "Check for Skim updates". 
@end itemize
@endbox

You can also check immediately for Skim updates yourself. Choose Skim > Check for Updates@dots{}.

@c ======================================================================================

@topic Emailing a PDF file loses notes or highlights

Notes and highlights you add to a PDF document are not saved in the PDF data, but are added to the file as extended attributes. Those are usually lost when you email the file. 

There are several ways to preserve the notes. Some compression methods preserve extended attributes. Apple's Create Archive unfortunately does not preserve them. You should compress and expand to test whether they are saved. You can also create a disk image to wrap the PDF file. Compression using tar and gzip also preserves the notes.

You can also save the notes to a separate .skim file. The receiver of the email can later add the notes to the PDF.

And lastly, you can save the PDF and notes in a PDF bundle, that wraps the PDF and the notes together.

@box{taskbox}
@heading To save the notes to a separate file:
@enumerate
@item Choose File > Export@dots{}. 
@item Select "Skim Notes" from the File Format popup, choose a location to save the notes to, and press OK. 
@end enumerate
@heading To add notes from a separate .skim notes file to a PDF file:
@enumerate
@item Open the PDF file.
@item Choose File > Read Notes@dots{}, and choose the .skim file that holds the notes. 
@end enumerate
@heading To create an archive of the PDF document:
@enumerate
@item Make sure you have saved the PDF file with the notes.
@item Choose File > Save Archive @dots{}, choose a location to save the archive to, and press OK.
@end enumerate
@heading To create a disk image of the PDF document:
@enumerate
@item Make sure you have saved the PDF file with the notes.
@item Choose File > Save Disk Image @dots{}, choose a location to save the disk image to, and press OK.
@end enumerate
@heading To save the PDF and notes to a bundle:
@enumerate
@item Choose File > Export@dots{}. 
@item Select "PDF Bundle" from the File Format popup, choose a location to save the bundle to, and press OK. 
@end enumerate
@endbox

It is important that the notes file is associated to the PDF file. Therefore it is best to choose the same file name for the .pdf file and the .skim file. In that case, Skim will automatically offer to add the notes from the notes file when you open the PDF file. 

@heading See also
@menu
* Adding notes to a PDF document::
* Highlighting sections of a PDF document::
* Saving notes and highlights to a separate file::
* Adding notes and highlights from a separate Skim notes file::
* Saving PDF and notes in a bundle::
@end menu

@c ======================================================================================

@topic Saving PDF and notes in a bundle

Notes and highlights you add to a PDF document are not saved in the PDF data, but are added to the file as extended attributes. Those can sometimes be lost when archiving the PDF file or sending it over email.

Alternatively, you can save the PDF and the notes wrapped in a bundle, with file extension pdfd.

@box{taskbox}
@heading To save the PDF and notes as a bundle:
@enumerate
@item Choose File > Save As@dots{}. 
@item Select "PDF Bundle" from the File Format popup, choose a location to save the PDF bundle, and press OK. 
@end enumerate
@heading To save a copy of the PDF and notes as a bundle:
@enumerate
@item Choose File > Export@dots{}. 
@item Select "PDF Bundle" from the File Format popup, choose a location to save the PDF bundle, and press OK. 
@end enumerate
@endbox

A PDF bundle contains the unmodified PDF file and files containing the notes. You can see those file in the Finder using the 'Show package Contents' contextual menu item.

@heading See also
@menu
* Emailing a PDF file loses notes or highlights::
* Saving PDF files without notes and highlights::
* Saving PDF files with the notes and highlights included::
* Saving notes and highlights to a separate file::
@end menu

@c ======================================================================================

@topic Saving notes and highlights to a separate file

Notes and highlights you add to a PDF document are not saved in the PDF data, but are added to the file as extended attributes. Those can sometimes be lost when archiving the PDF file or sending it over email.

You can save the notes to a separate .skim file, for backup or to send them by email. 

@box{taskbox}
@heading To save the notes to a separate file:
@enumerate
@item Choose File > Export@dots{}. 
@item Select "Skim Notes" from the File Format popup, choose a location to save the notes to, and press OK. 
@end enumerate
@endbox

It is important that the notes file is associated to the PDF file. Therefore it is best to choose the same file name for the .pdf file and the .skim file. In that case, Skim will automatically offer to add the notes from the notes file when you open the PDF file. 

@heading See also
@menu
* Adding notes and highlights from a separate Skim notes file::
* Emailing a PDF file loses notes or highlights::
* Saving notes and highlights as text::
* Adding notes to a PDF document::
* Highlighting sections of a PDF document::
@end menu

@c ======================================================================================

@topic Adding notes and highlights from a separate Skim notes file

You can have notes contained in a separate file with extension "skim", for backup or when the notes were send by email with the PDF file. 

You can add the notes to the companion PDF file. 

@box{taskbox}
@heading To add notes from a separate .skim notes file to a PDF file:
@enumerate
@item Open the PDF file.
@item Choose File > Read Notes@dots{}, and choose the .skim file that holds the notes. 
@end enumerate
@endbox

It is important that the notes file is associated to the PDF file. If the file name for the .pdf file and the .skim file are the same apart from the extension, Skim will automatically offer to add the notes from the notes file when you open the PDF file. 

@heading See also
@menu
* Saving notes and highlights to a separate file::
* Emailing a PDF file loses notes or highlights::
* Adding notes to a PDF document::
* Highlighting sections of a PDF document::
@end menu

@c ======================================================================================

@topic I don't see notes and highlights in other PDF viewers

Normally, Notes and highlights you add to a PDF document are not saved in the PDF data, but are added to the file as extended attributes. However, Skim allows you to save a copy of your PDF file that does contain the notes in the PDF data. This allows you to see the notes also in other PDF viewers. 

@heading See also
@menu
* Saving PDF files with the notes and highlights included::
@end menu

@c ======================================================================================

@topic PDF with fillable forms loses edits to the forms

Even though you can edit forms in PDF document that have them, those edits will not be saved. However, Skim allows you to save a copy of your PDF file that does contain the filled forms in the PDF data, by exporting it with embedded notes. This will also allow you to see the filled forms in other PDF viewers. However, after saving these edits, the forms will not be editable anymore.

@heading See also
@menu
* Saving PDF files with the notes and highlights included::
@end menu

@c ======================================================================================

@topic Saving PDF files with the notes and highlights included

Normally, Notes and highlights you add to a PDF document are not saved in the PDF data, but are added to the file as extended attributes. However, Skim allows you to save a copy of your PDF file that does contain the notes in the PDF data. This allows you to see the notes also in other PDF viewers. 

@box{taskbox}
@heading To save a copy of the PDF with notes included:
@enumerate
@item Choose File > Export@dots{}. 
@item Select "PDF" from the File Format popup, select the "With Embedded Notes" option, choose a location to save the PDF to, and press OK. 
@end enumerate
@endbox

@heading See also
@menu
* Saving PDF files without notes and highlights::
* I don't see notes and highlights in other PDF viewers::
@end menu

@c ======================================================================================

@topic Saving PDF files without notes and highlights

Skim allows you to save a copy of your PDF file without the notes and highlights. 

@box{taskbox}
@heading To save a copy of the PDF without notes:
@enumerate
@item Choose File > Export@dots{}. 
@item Select "PDF" from the File Format popup, select the "Without Notes" option, choose a location to save the PDF to, and press OK. 
@end enumerate
@endbox

@heading See also
@menu
* Saving PDF files with the notes and highlights included::
@end menu

@c ======================================================================================

@topic Saving notes and highlights as text

You can save notes added in Skim to a separately in human readable form to a Rich Text Format (RTF) file. 

@box{taskbox}
@heading To save the notes as RTF:
@enumerate
@item Choose File > Export@dots{}. 
@item Select "Notes as RTF" from the File Format popup, choose a location to save the notes to, and press OK. 
@end enumerate
@endbox

@heading See also
@menu
* Saving notes and highlights to a separate file::
* Adding notes to a PDF document::
* Highlighting sections of a PDF document::
@end menu

@c ======================================================================================

@topic Automating tasks with AppleScript

Skim is a scriptable application. It responds to AppleScript commands that let you automate Skim. 
For example, you can change the colors of all notes or highlights of a certain type, automatically add or remove highlights, and much more.

@box{taskbox}
@heading To see the commands you can use with Skim:
@enumerate
@item Open the Script Editor application. 
@item Choose Window > Library or File > Open Dictionary@dots{}, and then click Skim. You may need to add Skim to the list first.
@end enumerate
@endbox

@heading Open this for me
@multitable {}
@item @uref{http://sourceforge.net/p/skim-app/wiki/AppleScript, AppleScript page on the Skim Wiki}
@item @uref{help:runscript=SkimHelp/scripts/OpenAppDict.scpt string='net.sourceforge.skim-app.skim', Skim dictionary in Script Editor}
@item @uref{help:anchor='access' bookID=AppleScript Help, AppleScript Help}
@item @uref{http://www.apple.com/macosx/features/applescript/, AppleScript website}
@end multitable

@c ======================================================================================

@topic PDF-TeX synchronization

Skim supports SyncTeX and PDFSync to synchronize between a line in a TeX source file and the generated output PDF file.
To enable PDF-TeX synchronization, you need to setup Skim and your favorite editor to know about each other.

@box{taskbox}
@itemize
@item To display the TeX source line corresponding to a point in the PDF document, hold down the Shift and Apple key and click on a point in the PDF document.
@end itemize
@itemize
@item To choose the command to open the TeX editor, choose Skim > Preferences, click Sync, and choose a preset editor, or choose Custom and enter a path to an editor command and arguments.
@end itemize
@endbox

Check the Skim Wiki for more details, in particular about how to set up various editors to use Skim's TeX-PDF synchronization.

@heading Open this for me
@multitable {}
@item @uref{http://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization, TeX-PDF Synchronization page on the Skim Wiki}
@end multitable

@c ======================================================================================

@node More information
@chapter More information
@abstract{Getting more help}

@heading Online Resources
@itemize
@item @uref{http://skim-app.sourceforge.net, Skim Website}
@item @uref{http://sourceforge.net/p/skim-app/wiki/, Skim Wiki}
@item @uref{http://sourceforge.net/p/skim-app/wiki/FAQ, Skim FAQ}
@item @uref{http://skim-app.sourceforge.net/manual, Online copy of this manual}
@end itemize

@heading Mailing List

If your questions aren't answered in this help file, the
@uref{https://lists.sourceforge.net/lists/listinfo/skim-app-users, skim-users mailing list} 
may have an answer. Your question
may have been answered already, so you can check the 
@uref{https://sourceforge.net/mailarchive/forum.php?forum=skim-app-users,list archives} 
to get instant gratification.

@heading Bug reports

You can submit a bug report to the bug tracker at 
@uref{https://sourceforge.net/projects/skim-app}.

The reports are most useful if they provide a clear description of
what went wrong, what you expected, and how to reproduce the problem
at a different computer without you there helping us.

If you're submitting a problem with how it handled a certain file, it
would help if you sent that file too. Crash reports are also useful and can
be obtained from the Console application (in `Applications/Utilities`).


@c ======================================================================================
@c INDEXES
@c ======================================================================================

@node indexcp
@appendix Help Topics
@abstract{Help Topics}

Click a topic below.

@printindex cp

@bye
