#!/usr/bin/perl -w

print "\n*******************************\n";
print "Welcome to BibDesk development.\n";
print "This script will get the stuff you need from cvs to build bibdesk.\n";
print "Developers should set SF_USERNAME to use ssh access\n";

$SFNAME=getSFName();

if ($SFNAME ne "") {
    prepdev();
} else {
    prepanon();
} 
$bibtag=gettag();

getsources();

print "\n****************************\n";                     
print "getBibdeskCVS done.\n";  
print "To Build properly you must have your Build Preferences set\n";
print "to \"Separate Location for Build Products\"\n\n";
print "Remember to build the \"Build me First\" target, well, before\n";
print "building the bibdesk target.\n";

print "Do you want to open the project file (bibdesk/Bibdesk.xcode) now? (y/n)\n";
system 'open bibdesk/Bibdesk.xcode' if <STDIN> =~ /^y/;

sub getSFName {
  if (defined $ENV{'SF_USERNAME'} ) { 
	return $ENV{'SF_USERNAME'};
  } else {
      print "Are you a developer using ssh access (y/n)? ";
      $DEV = <STDIN>;
      if ( $DEV =~ /^n/ ) {
	  return "";
      } else {
         print "What is your sourceforge username (setenv SF_USERNAME for a default)?  ";
         $SFNAME = <STDIN>;
	 chomp($SFNAME);
         return $SFNAME;
      }
  }
}


# Set the BIB tag
sub gettag {
 if (defined $ENV{'SF_BIB_TAG'} ) {
   $bibtag = $ENV{'SF_BIB_TAG'};
 } else {
   print "Do you want a specific tag? (empty for none or enter tag (eg BR_1x)): ";
   $bibtag = <STDIN>;
 }
 chomp($bibtag);
 if ($bibtag eq "") {
   return $bibtag;
 } else {
   return "-r $bibtag";
 }
}

sub prepanon {
  $CVS_METHOD = "pserver";
  $SFNAME = "anonymous";
  $LOGIN = "cvs -z3 -d:$CVS_METHOD:$SFNAME\@cvs.sourceforge.net:/cvsroot/bibdesk login";
  print "$LOGIN\n";
  print "\nPassword is empty--just hit return when asked for a password\n";
  tryGet($LOGIN);
}

sub prepdev {
  $ENV{'CVS_RSH'} = 'ssh';
  $CVS_METHOD = "ext";
}

sub getsources {
   $GETMAIN = "cvs -z3 -d:$CVS_METHOD:$SFNAME\@cvs.sourceforge.net:/cvsroot/bibdesk checkout -P $bibtag bibdesk";
   tryGet($GETMAIN);

   $GETVENDOR = "cvs -z3 -d:$CVS_METHOD:$SFNAME\@cvs.sourceforge.net:/cvsroot/bibdesk checkout -P bibdesk_vendorsrc";
   tryGet($GETVENDOR);
   
   $GETINPUTMANAGER = "cvs -z3 -d:$CVS_METHOD:$SFNAME\@cvs.sourceforge.net:/cvsroot/bibdesk checkout -P bibdeskinputmanager";
   tryGet($GETINPUTMANAGER);

}

sub tryGet {
  $toGet = shift;

  print "Executing: $toGet\n";
       
  if ( (system $toGet) != 0) { #return of 0 indicates success
     print "cvs failed.  Check messages above. Should I try again? (y/n)?";
     undef $tryAgain;
     $tryAgain = <STDIN>;
       
     if ($tryAgain =~  /^y/) {
       getsources();
     } else {
      print "cvs failed.  Please read messages above and";
      print " try again in a few moments\n";
      exit;
     }
  } 
}
