#!/usr/bin/perl -w

print "\n*******************************\n";
print "Welcome to BibDesk development.\n";
print "This script will get the stuff you need from Subversion to build bibdesk.\n\n";

getsources();

print <<ENDHERE;

getBibdeskSVN done.  
****************************

Build Instructions
-----------------
(Also check http://bibdesk.sourceforge.net/wiki/index.php/BuildingFromSVN )

1. You must have the Cross Compling tools, which are a customize
   option during the Xcode install.  This avoids 
   "/Developer/SDKs/MacOSX10.4u.sdk does not exist" type errors
    
2. In Xcode, Set Build Preferences to "Separate Location for Build Products"
   (This is required by the OmniFrameworks, but is good practice anyway)

3. Remember to build the "Build me First" target before trying to 
   build the bibdesk target. (builds frameworks etc)
    
Do you want to open the project file (bibdesk/Bibdesk.xcodeproj) now? (y/n)
ENDHERE

system 'open bibdesk/Bibdesk.xcodeproj' if <STDIN> =~ /^y/;

sub getsources {
   $GETMAIN = "svn co https://bibdesk.svn.sourceforge.net/svnroot/bibdesk/trunk/bibdesk bibdesk";
   tryGet($GETMAIN);

   $GETVENDOR = "svn co https://bibdesk.svn.sourceforge.net/svnroot/bibdesk/trunk/bibdesk_vendorsrc bibdesk_vendorsrc";
   tryGet($GETVENDOR);
   
   $GETINPUTMANAGER = "svn co https://bibdesk.svn.sourceforge.net/svnroot/bibdesk/trunk/bibdeskinputmanager bibdeskinputmanager";
   tryGet($GETINPUTMANAGER);

}

sub tryGet {
  $toGet = shift;

  print "Executing: $toGet\n";
       
  if ( (system $toGet) != 0) { #return of 0 indicates success
     print "svn failed.  Check messages above. Should I try again? (y/n)?";
     undef $tryAgain;
     $tryAgain = <STDIN>;
       
     if ($tryAgain =~  /^y/) {
       getsources();
     } else {
      print "svn failed.  Please read messages above and";
      print " try again in a few moments\n";
      exit;
     }
  } 
}
