.TH LATEX2PNG "1" "November 2002" "latex2png 1.1\n" "User Commands"
.SH NAME
latex2png \- manual page for latex2png 1.1
.SH DESCRIPTION
latex2png \fB\-\-\fR Convert a LaTeX file to a PNG image
.PP
USAGE: latex2png [-d density] [-h] [-k] [-c] [-g] [-m] [-H home dir] file[.tex|.eps]
.PP
The
.I latex2png
command converts a LaTeX file into a PNG image.  The first page is
translated into an image at the specified resolution.  
.I latex2png
can also be used to convert encapsulated postscript (EPS) files to
PNG images.  
.SS "OPTIONS:"
.HP
\fB\-c\fR produce color image
.TP
\fB\-d\fR density
.I density 
is  the number of dots per inch to use in the created image
(default 144 dpi)
.HP
\fB\-g\fR produce gray images
.TP
\fB\-h\fR help
.TP
\fB\-H\fR home_dir
.I home_dir 
is a directory to be included in search path (default is directory
that contains the LaTeX file).  This is used to create PNG images in
another directory (e.g., /tmp) and still allow LaTeX to find files
that it needs to include.
.TP
\fB\-k\fR keep intermediate files (for debugging)
.TP
\fB\-m\fR produce monochrome (black and white) image
(default)
.TP
\fB\-v\fR version
.SS "EXAMPLES:"
.TP
latex2png \fB\-d\fR 144 /tmp/file
#create /tmp/file.png at 144 dpi
.TP
latex2png file.eps
#create file.png
.TP
latex2png file.tex
#create file.png via latex
.TP
latex2png \fB\-H\fR . /tmp/file
#search the cwd for image files
.SH "SEE ALSO"
.B latex2png
is a part of 
.B latex2rtf
and has a special mode to assist in finding the baseline of a latex
equation.  Documentation for 
.B latex2rtf 
may be found
in
.B latex2rtf.info,
the PDF file
.B latex2rtf.pdf
or the HTML file
.B latex2rtf.html
which are made from the TeXInfo source file
.BR latex2rtf.texi.